sudo: false

language: go

go:
  - "1.14.x"

env:
  global:
  - REPO=grepplabs/kafka-proxy
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - secure: P1SisTOejJOocbI22Z8iLknctJcxOPsW2kXn4n25gz53ZounZgoPLqaTmrXdwlaKcAgVFv31ZumyfA14mBI/MZ4EC8sdTjdFMgfa5QuuK88mYq03GsxG8Von7R7sW4j0rxuWtNA0EnZQuBjVm2u4KX+RYs+kYBcD20K3uqQlEQDqMRpqNudpti7O3IBvufnbDqtXkHT+fUwC6l/uxXwhn0HE251xYdR1tiYg4FOFeDZ7LUohU+e1vGJqQjAnJy2HK9T5fomakRCOUEO+p6JfpXL5QPm78iWhaWwXr4Ybi5YLWFIYH1oAHMEsx8oX026t33TfvyVg8JOwQtWp/uECFCNCwLhkxZjLvA6mpkCqrUuNzQoGNteSR/wq1IdS+iR/jzHNGo89a+eCawIRB6NFPwYCTgo0Fwm0IpZQFLwwp9naoX28XVCMYdEQUP77Ln81+tPr2BSTp0kaMrSStgOoO9WpD8akqVJU5uWY4E7RCKY09HvVUaLTLFtK9vVfhnZVDF0gAiMIiq2zsBkG1Ak/KxD9Xq6W8QjQelPHWkEDWvsLNfz1sOUWNlO4rYVZ6Ai0HvxmDiPqkO/n25EZmjTMsVyW1oEyfs2eUJDaTGTVZqzEmRiEu5XUupukfvXUvByiBe7Y/BheLH7Q2SHc8GxNebVOlRvdksJJTGqE3LzsrIg=
  - secure: b8jLihZE/quAbjK/2ZYQ4FhDmJsnwdlEXvX/eT1/NV5ImTuwZv/+f6LVCqOQnrU0xQKD8fQe+QYr/+wCWwEcBTNf0NgEYiYZAtr7xvKpVq2A76ghAH3zg5MslzQfPcfaW+c+tYBiJWrya0QmPEW53c1krYRyQ5oHASt/KnQG9YSIxv5Scq/Ucan4UugIvB+45k4CbDcwZXSLQWzP+Wa93LDNU0qjysN8FL/sQWOVy/Rkb4dFHND18iP+qCCklgRmq4ztsJ3/gUZ4zJylfbSOT80tIKUx74ySudmBFMNGZjKIu+U2muXXihc0lSJ1qXQaXZAFC91/QzzR2guzVqMlW3dVG+YLI157Pp5wiGfkW/sf3whJcOsbgc15tr3B7xLW4HiwvnganzjBqxMkOMLrW8brtZoFWBtqw9BwTzg2U5RbAK8BZ+lPwyNNrCGrt2nG//FN5iONV4uCwDi5sHS1GL4cSDZRc95d1lGpqjHSwW1fXeL3gz2PPJgjMgizempu3HGn4m2RgWkhsxuB5/A2lfdZ5uUQgG5kIOLUx0nArjNiw5zelCWMbZDMB0BDdZ1vLFH0iFCF2nAdNicDgQ5dgv5X5fNeNT7cgV4TQo1fBbLLoAB3WTyAQNdem/Gt+pwj3dN0gLwU1S0RkQQDDU0R/0CJTnz3CwJRIQVJooHG6yI=
services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - go build .
  - go test ./...
  - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo "${TRAVIS_PULL_REQUEST_BRANCH:-${TRAVIS_BRANCH}}"; fi`
  - echo "docker tag $TAG"
  - docker build -t $REPO:$TAG -f Dockerfile .

after_success:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
       docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
    fi
  - docker push $REPO:$TAG
